# Generated by Django 2.1.4 on 2018-12-18 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20181218_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='expert',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestexpert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_chat',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to=settings.AUTH_USER_MODEL),
        ),
    ]
