# Generated by Django 2.1.4 on 2018-12-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20181218_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_chat',
            name='type',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
