# Generated by Django 2.1.4 on 2018-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_botchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchat',
            name='descrip',
            field=models.CharField(max_length=750),
        ),
    ]
