# Generated by Django 2.1.4 on 2018-12-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20181221_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(max_length=750)),
            ],
        ),
        migrations.RemoveField(
            model_name='botchat',
            name='descrip',
        ),
        migrations.AddField(
            model_name='botdesc',
            name='botchat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.BotChat'),
        ),
    ]
