# Generated by Django 2.1.4 on 2018-12-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
