# Generated by Django 2.1.4 on 2018-12-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='request_type',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Services', 'Services'), ('Insurance', 'Insurance'), ('Other', 'Other')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
