# Generated by Django 2.1.4 on 2018-12-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_chatrequest_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrequest',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='requestdata',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Services', 'Services'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=10),
        ),
    ]
