# Generated by Django 2.1.4 on 2018-12-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_userprofile_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='locations',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
