# Generated by Django 2.1.4 on 2018-12-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_chatrequest_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='status',
            field=models.CharField(choices=[('Panding', 'Panding'), ('Success', 'Success'), ('Expired', 'Expired')], default='Panding', max_length=10),
        ),
    ]
